server:
  port: 80
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/security?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: root
      filters: log4j,wall,mergeStat
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true